/**
 * Primitive types that has its own format and properties that cannot be described with TypeScript type system. 
 * 
 * E.g. HTML and URL has a certain format but are represented as `string` in Typescript.
 * @namespace BasicTypes
 */

/**
 * ID of a node (a page of the website)
 * @typedef {string} BasicTypes.NodeId
 */

/**
 * ID of a scope, which is a collection of nodes with a head node.
 * @typedef {string} BasicTypes.ScopeId
 */

/**
 * HTML generated by a markdown parser in the backend. This is a type for most page contents that are unstructured.
 * @typedef {string} BasicTypes.HTMLContent
 */

/** 
 * A union type of the following:
 * 1. a normal website URL
 * 2. a relative path that grabs media from the server
 * @typedef {string} BasicTypes.URL
 */

 exports.unused = {};